# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import slideshow.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=slideshow.models.upload_image_path)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bootstrap_class_active', models.CharField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carousel',
            name='carouselement',
            field=models.ManyToManyField(to='slideshow.Slide', verbose_name='Slideshow'),
        ),
    ]
