# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pais',
        ),
    ]
