# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_presentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='presentation',
            field=models.CharField(default='unidad', max_length=120),
        ),
    ]
