# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='step',
        ),
    ]
