# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogcategory',
            old_name='catalog',
            new_name='category',
        ),
    ]
