# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181120_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
