# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181120_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcategory',
            name='en_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='en_title',
            field=models.CharField(default='', max_length=300),
        ),
    ]
