# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-02-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160211_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.CharField(choices=[('unit', 'Unit'), ('weigth', 'Weight')], default='unit', max_length=120),
        ),
    ]
