# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20160211_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='presentation',
            field=models.CharField(choices=[('unit', 'unidad'), ('weigth', 'kilo')], default='unit', max_length=120),
        ),
    ]
