# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-23 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181123_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='presentation',
            field=models.CharField(choices=[('unidad', 'unidad'), ('kilo', 'kilo')], default='unit', max_length=120),
        ),
    ]
