# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181123_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='inventory',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
