# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20181126_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='presentation',
            field=models.CharField(choices=[('unidad', 'unidad'), ('peso', 'kilo')], default='unidad', max_length=120),
        ),
    ]
