# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20181126_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='variation',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True),
        ),
    ]
