# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variation_min_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.CharField(default=2, help_text='En que presentación se vende el producto', max_length=120),
            preserve_default=False,
        ),
    ]
