# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20181227_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='step',
            field=models.DecimalField(choices=[('peso', '0.2'), ('unidad', '1')], decimal_places=2, default=0, max_digits=6),
        ),
    ]
