# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_variation_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='en_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='en_title',
            field=models.CharField(default='', help_text='Digite el nombre del producto', max_length=120),
        ),
    ]
