# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20190122_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='en_presentation',
            field=models.CharField(choices=[('unidad', 'la unidad'), ('peso', 'Kilo')], default='unidad', max_length=120),
        ),
        migrations.AddField(
            model_name='variation',
            name='en_title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
