# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_productfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(upload_to='upload_product_file_loc'),
        ),
    ]
