# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-05 23:33
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20190605_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/caesar/django/ecommerce/ecommerceVer/ecommerceV19_9_slideapp_menu_digital/static_cdn/protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
