# Generated by Django 3.2.9 on 2021-11-15 20:36

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200606_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\50687\\Desktop\\New folder\\code\\code_django\\ecommerce-caesae2\\ecommerce-caesae\\static_cdn\\protected_media'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
